Guns feature
BenDBrown/MayGameJam pull request #71
Opened 2024-12-06 04:57 UTC by Laijen

# Context
This pull was made regarding the Guns Task on Trello.

You can switch between different types of gun. For this I made use of the existing gun group implementation and created a weapon menu system. This makes uses of an template UI. To switch between guns, you need to hold the "Tab" button and then scroll with your mouse wheel to select the gun you want. The moment you switch your gun it is saved and you can release the "Tab" button to make the menu dissappear again. I added placeholder icons for the gun types.

I added sounds to when a bullet hits another ship. I made use of the existing sound FX. I created a new node similar to SingleAnimationRun, which is called SingleAudioRun. I added this to the Gun prefab, which will receive the right data through additional data on the GunData resources. 

After a bullet collides, a short animation will be played. This animation is the "Bullet Explosion" animation that was in the project.

# Additions
* Gun Switching System & UI Controls
* Placeholder Guntypes Icons
* Single Sound Player for hitmarkers
* Explosion animation for when bullets collide
* Weapon Menu UI prefab
* Weapon Menu Option Prefab: This is just a single square box representing one of the options in the weapon menu.

# Modified
* GunData to add additional variables for the weapon menu and shooting audio
* Several Gun resources to set the right data for the gun itself such as icon and audio
* Bullet & Laser prefab added explosion animation
* Bullet script to add the animation and sound functionality
* gun scrtipt to add the sound functionality, the guntype icon is saved here for the weapon menu
* Added guntypes: cannon and laser
* GunGroup script to contain the gunTypeIcon
* GunManager script to allow the weapon menu to find the selected weapon, functionality to cycle weapons through the playercontroller, 
* PlayerController script to add the buttons for gun switching
* Playership script to add functionality for the weapon menu
* Ship to add the right methods to cycle
* Gun prefab to add the Audio prefabs
* Hud prefab to add the weapon menu
* Godot Project to add the button mapping

* Playershield --> No idea what happened here. I haven't checked whether its important...

# Removed
Nothing

# Asset Change
Nothing

# Bug
* If you switch weapons while shooting, the initial weapon will keep shooting even without being selected or the mouse button pressed.
* The bullet explosion animation happens while the bullet is traveling
* The hitmarker sound also playing when the enemy hits the player

# Bug Fix
Nothing

2024-12-06 09:22 UTC, MelodyTheMuse requested changes
FIX BUGS
Shield not working on Ismet's system
My system, spam clicking stuck is back
Look into the shielding path and check if it needs to be fixed
These need to be fixed before merge

2024-12-09 13:04 UTC, GenelleGeerman commented
![](https://github.trello.services/images/mini-trello-icon.png) [[HIGH AF PRIO] Guns](https://trello.com/c/4D1RRpwM/229-high-af-prio-guns)

2024-12-16 00:28 UTC, GenelleGeerman requested changes

2024-12-16 00:28 UTC, GenelleGeerman commented on Resources/Scripts/ComponentData/GunData.cs
> +	public AudioStream ShootingAudio;
ShootingAudio is kinda vague, ShootSFX is more clear.
shootingAudioFromPosition should be named ShootingAudioFromPosition.
Same issue with shootingAudioEndPosition.
The name is clear for me but it might be a bit confusing so add a bit of explanation.
For ShootingAudioEndPosition, having -1 is kind of difficult if you don't look at the code. Add a hover text saying that.

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Components/Bullet.cs
> +        if(area.GetParent().GetParent() is Ship){ //Todo: Better definition for enemies should be made
Knowing How AttackComponents work, this isn't needed and also is the wrong way to build it. Bullet shouldn't know what it hits, what gets hit needs to know it was hit by a bullet. Otherwise this method becomes 400 lines long because you have to check for every possible interaction which is impossible.

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Components/Bullet.cs
> +            EmitSignal(SignalName.Hit);
not sure what this does as there is nothing written

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Components/Gun.cs
> +		bullet.Hit += PlayHitAudio;
Why not have bullet contain an audio source?

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Components/Gun.cs
> +			shootingAudio.fromPosition = gunData.shootingAudiofromPosition;
bulletPrefab.audioStream = gunData.ShootingAudio. Makes it easier

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Components/Gun.cs
> +			shootingAudio.fromPosition = gunData.shootingAudiofromPosition;
The reason for this is imagine an enemy shoots a bullet but the ship gets destroyed before the bullet hits something. No sound will play

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Managers/GunManager.cs
> +	public void CycleGunGroupUp() => CycleGunGroup(-1);
I understand that the logic might require this to be this way, but it is a bit unclear and looks like a smell. 2 fixes, either change the code to have cycleUp be 1 or create an enum that has that value. CYCLE_UP = 1. Prefer the former over the latter.

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Managers/GunManager.cs
> +			return null;	// Todo: Add an exception for when the type is not found. There is no default icon as of now, which will also solve this.
Try not to return null when possible. Return a new Texture2D but this is fine. Even if you need to check type, it is better to paste a warning that there is no texture than to leave it like this

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/Managers/GunManager.cs
> +		else if(newIndex == gunGroups.Count){ // Loop to beginning
Make sure you use >=. If not, what happens if count is 2, and I somehow make newIndex 3?

2024-12-16 00:28 UTC, GenelleGeerman commented on Ship/Scripts/PlayerShip.cs
> +		// Todo: Redundant as using the method CycleGunGroup in gunmanager is easier than using the Up and Down method. Maybe only for normal ships. Ask Genelle or Ben
You have last say in this, so just do it rather than ask. You saw something that you found to be bad practice/code smell. Act upon it. You were right in this case

2024-12-16 00:28 UTC, GenelleGeerman commented on UI/Scripts/WeaponMenuOption.cs
> +	public override void _Ready()
remove if empty

2024-12-16 00:28 UTC, GenelleGeerman commented on UI/Scripts/WeaponMenuOption.cs
> +public enum WeaponBorderState {
not in the manifesto but either place it in its own file, or place it at the top. This would be hard to find

2024-12-16 00:29 UTC, GenelleGeerman commented
@Laijen We can discuss this this week if you'd like. Send me a date and time that you can.

2024-12-23 15:41 UTC, GenelleGeerman requested changes
Remove the 2 .tmp files and it will be merged in

2024-12-23 15:41 UTC, GenelleGeerman commented on Scenes/lev2B47.tmp
remove this.

2024-12-23 15:41 UTC, GenelleGeerman commented on Scenes/levD0D7.tmp
remove this

2024-12-23 15:41 UTC, GenelleGeerman commented on Ship/Scripts/Components/Gun.cs
this is fine, but try not to mix Gun and UI too much. No change needed now but Ideally, the UI knows what Icon it needs to display depending on the the Gun's Type.

2024-12-23 15:41 UTC, GenelleGeerman commented on UI/Scripts/WeaponBorderState.cs
This can be reused other places. So calling it something like SelectionState might be better. No change needed.

2024-12-23 16:17 UTC, merged